feature: feedback form
CodeForPhilly/balancer-main pull request #31
Opened 2023-09-19 21:03 UTC by kristo-baricevic

Added Feedback.tsx and FeedbackForm.tsx, changed link in navbar to include feedback endpoint

2023-09-19 21:43 UTC, ryanrrogers requested changes
Just throw that .ds_store file in the .gitignore and all is good 👍

2023-09-19 21:43 UTC, ryanrrogers commented on .DS_Store
Do you mind adding this to the .gitignore? If you aren't familiar with these, these are generated by macos and generally shouldn't be included.

2023-09-20 12:20 UTC, kristo-baricevic commented on .DS_Store
Hey, I’m away from my computer until tonight but I will do this asap unless I get some time to try it on mobile

2023-09-21 04:21 UTC, kristo-baricevic commented on .DS_Store
I added it - but I noticed it was already there. I manually deleted .DS_store but am not sure why it was added despite being in gitignore

2023-09-21 14:10 UTC, ryanrrogers commented on .DS_Store
Odd, it might be a weird pathing issue with the .gitignore

2023-09-21 14:15 UTC, ryanrrogers approved these changes

2023-09-21 14:15 UTC, merged